image: node:16.13.0
pipelines:
  branches:
    master:
      - step:
          name: Siga Backend Master
          script:
            - rm -rf package-lock.json
            - rm -rf node_modules
            - npm install
      - step:
           name: Deploy to heroku Production
           deployment: production
           script:
            - echo "Deploying in $HEROKU_APP_NAME"
            - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $BITBUCKET_BRANCH:master
            - echo "Deployed - https://siga-unca.herokuapp.com/"
    develop:
      - step:
          name: Siga Backend Develop
          script:
            - rm -rf package-lock.json
            - rm -rf node_modules
            - npm install
      - step:
           name: Deploy to heroku Develop
           deployment: develop
           script:
            - echo "Deploying in $HEROKU_APP_NAME"
            - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $BITBUCKET_BRANCH:master
            - echo "Deployed - https://siga-unca-dev.herokuapp.com/"
    testing:
      - step:
          name: Siga Backend Testing
          script:
            - rm -rf package-lock.json
            - rm -rf node_modules
            - npm install
      - step:
           name: Deploy to heroku Testing
           deployment: testing
           script:
            - echo "Deploying in $HEROKU_APP_NAME"
            - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $BITBUCKET_BRANCH:master
            - echo "Deployed - https://siga-unca-test.herokuapp.com/"