const Persona = require("../../../models/Persona");
const colors = require("colors/safe");

exports.createPersonasPadres = async () => {
    console.log(colors.cyan("Persona - Madres"))

  const personaMadre1 = await Persona({
    nombres: "Madre",
    apellidos: "N° 1",
    numeroDocumento: "3333331",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1969-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Parque chacabuco",
    domicilioCalle: "Presidente castillo",
    domicilioNumeroCalle: 25,
    domicilioPiso: 0,
    domicilioDepartamento: null,
    ocupacion: "Maestra Jardinera",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Esquiu",
    domicilioLaboralNumeroCalle: 345,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111114",
    contactoTelefonoSec: "1511111113",
    contactoCorreo: "madre1@dominio.com"
  }).save();

  const personaMadre2 = await Persona({
    nombres: "Madre",
    apellidos: "N° 2",
    numeroDocumento: "3333332",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1969-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Parque chacabuco",
    domicilioCalle: "Presidente castillo",
    domicilioNumeroCalle: 25,
    domicilioPiso: 0,
    domicilioDepartamento: null,
    ocupacion: "Abogada",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Salta",
    domicilioLaboralNumeroCalle: 23,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "3834564564",
    contactoTelefonoSec: null,
    contactoCorreo: "madre2@dominio.com"
  }).save();

  const personaMadre3 = await Persona({
    nombres: "Madre",
    apellidos: "N° 3",
    numeroDocumento: "3333333",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1969-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Parque chacabuco",
    domicilioCalle: "Presidente castillo",
    domicilioNumeroCalle: 25,
    domicilioPiso: 0,
    domicilioDepartamento: null,
    ocupacion: "Empleada pública",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Republica",
    domicilioLaboralNumeroCalle: 456,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111114",
    contactoTelefonoSec: "1511111113",
    contactoCorreo: "madre3@dominio.com"
  }).save();

  const personaMadre4 = await Persona({
    nombres: "Madre",
    apellidos: "N° 4",
    numeroDocumento: "3333334",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem", 
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Av. Belgrano",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "3834662254",
    contactoTelefonoSec: "3834554548",
    contactoCorreo: "madre@dominio.com"
  }).save();

  
  const personaMadre5 = await Persona({
    nombres: "Madre",
    apellidos: "N° 5",
    numeroDocumento: "3333335",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem", 
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Av. Belgrano",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "3834662254",
    contactoTelefonoSec: "3834554548",
    contactoCorreo: "madre@dominio.com"
  }).save();
  
  const personaMadre6 = await Persona({
    nombres: "Madre",
    apellidos: "N° 6",
    numeroDocumento: "3333336",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem", 
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Av. Belgrano",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "3834662254",
    contactoTelefonoSec: "3834554548",
    contactoCorreo: "madre@dominio.com"
  }).save();
  
  const personaMadre7 = await Persona({
    nombres: "Madre",
    apellidos: "N° 7",
    numeroDocumento: "3333337",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem", 
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Av. Belgrano",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "3834662254",
    contactoTelefonoSec: "3834554548",
    contactoCorreo: "madre@dominio.com"
  }).save();
  
  const personaMadre8 = await Persona({
    nombres: "Madre",
    apellidos: "N° 8",
    numeroDocumento: "3333338",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem", 
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Av. Belgrano",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "3834662254",
    contactoTelefonoSec: "3834554548",
    contactoCorreo: "madre@dominio.com"
  }).save();
  
  const personaMadre9 = await Persona({
    nombres: "Madre",
    apellidos: "N° 9",
    numeroDocumento: "3333339",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem", 
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Av. Belgrano",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "3834662254",
    contactoTelefonoSec: "3834554548",
    contactoCorreo: "madre@dominio.com"
  }).save();
  
  const personaMadre10 = await Persona({
    nombres: "Madre",
    apellidos: "N° 10",
    numeroDocumento: "3333310",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem", 
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Av. Belgrano",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "3834662254",
    contactoTelefonoSec: "3834554548",
    contactoCorreo: "madre@dominio.com"
  }).save();
  
  const personaMadre11 = await Persona({
    nombres: "Madre",
    apellidos: "N° 11",
    numeroDocumento: "3333311",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem", 
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Av. Belgrano",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "3834662254",
    contactoTelefonoSec: "3834554548",
    contactoCorreo: "madre@dominio.com"
  }).save();
  
  const personaMadre12 = await Persona({
    nombres: "Madre",
    apellidos: "N° 12",
    numeroDocumento: "3333312",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem", 
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Av. Belgrano",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "3834662254",
    contactoTelefonoSec: "3834554548",
    contactoCorreo: "madre@dominio.com"
  }).save();
  
  const personaMadre13 = await Persona({
    nombres: "Madre",
    apellidos: "N° 13",
    numeroDocumento: "3333313",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem", 
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Av. Belgrano",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "3834662254",
    contactoTelefonoSec: "3834554548",
    contactoCorreo: "madre@dominio.com"
  }).save();
  
  const personaMadre14 = await Persona({
    nombres: "Madre",
    apellidos: "N° 14",
    numeroDocumento: "3333314",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem", 
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Av. Belgrano",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "3834662254",
    contactoTelefonoSec: "3834554548",
    contactoCorreo: "madre@dominio.com"
  }).save();
  
  const personaMadre15 = await Persona({
    nombres: "Madre",
    apellidos: "N° 15",
    numeroDocumento: "3333315",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem", 
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Av. Belgrano",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "3834662254",
    contactoTelefonoSec: "3834554548",
    contactoCorreo: "madre@dominio.com"
  }).save();
  
  const personaMadre16 = await Persona({
    nombres: "Madre",
    apellidos: "N° 16",
    numeroDocumento: "3333316",
    tipoDocumento: "DNI",
    genero: "Femenino",
    grupoFactor: "A+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem", 
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Av. Belgrano",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "3834662254",
    contactoTelefonoSec: "3834554548",
    contactoCorreo: "madre@dominio.com"
  }).save();
  
  console.log(colors.cyan("Persona - Padres"));
    
  const personaPadre1 = await Persona({
    nombres: "Padre",
    apellidos: "N° 1",
    numeroDocumento: "4444441",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Chacabuco",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111115",
    contactoTelefonoSec: "1511111114",
    contactoCorreo: "padre1@dominio.com"
  }).save();
  
  const personaPadre2 = await Persona({
    nombres: "Padre",
    apellidos: "N° 2",
    numeroDocumento: "4444442",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alemn",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Av. Belgrano",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111115",
    contactoTelefonoSec: "1511111114",
    contactoCorreo: "padre2@dominio.com"
  }).save();
  
  const personaPadre3 = await Persona({
    nombres: "Padre",
    apellidos: "N° 3",
    numeroDocumento: "4444443",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alemn",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Av. Belgrano",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111115",
    contactoTelefonoSec: "1511111114",
    contactoCorreo: "padre3@dominio.com"
  }).save();

  const personaPadre4 = await Persona({
    nombres: "Padre",
    apellidos: "N° 4",
    numeroDocumento: "4444444",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alemn",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Esquiu",
    domicilioLaboralNumeroCalle: 342,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "3834659585",
    contactoTelefonoSec: "3834655655",
    contactoCorreo: "padre@dominio.com"
  }).save();

  const personaPadre5 = await Persona({
    nombres: "Padre",
    apellidos: "N° 5",
    numeroDocumento: "4444445",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Chacabuco",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111115",
    contactoTelefonoSec: "1511111114",
    contactoCorreo: "padre1@dominio.com"
  }).save();

  
  const personaPadre6 = await Persona({
    nombres: "Padre",
    apellidos: "N° 6",
    numeroDocumento: "4444446",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Chacabuco",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111115",
    contactoTelefonoSec: "1511111114",
    contactoCorreo: "padre1@dominio.com"
  }).save();

  
  const personaPadre7 = await Persona({
    nombres: "Padre",
    apellidos: "N° 7",
    numeroDocumento: "4444447",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Chacabuco",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111115",
    contactoTelefonoSec: "1511111114",
    contactoCorreo: "padre1@dominio.com"
  }).save();

  
  const personaPadre8 = await Persona({
    nombres: "Padre",
    apellidos: "N° 8",
    numeroDocumento: "4444448",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Chacabuco",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111115",
    contactoTelefonoSec: "1511111114",
    contactoCorreo: "padre1@dominio.com"
  }).save();


  
  const personaPadre9 = await Persona({
    nombres: "Padre",
    apellidos: "N° 9",
    numeroDocumento: "4444449",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Chacabuco",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111115",
    contactoTelefonoSec: "1511111114",
    contactoCorreo: "padre1@dominio.com"
  }).save();

  
  const personaPadre10 = await Persona({
    nombres: "Padre",
    apellidos: "N° 10",
    numeroDocumento: "4444410",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Chacabuco",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111115",
    contactoTelefonoSec: "1511111114",
    contactoCorreo: "padre1@dominio.com"
  }).save();

  
  const personaPadre11 = await Persona({
    nombres: "Padre",
    apellidos: "N° 11",
    numeroDocumento: "4444411",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Chacabuco",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111115",
    contactoTelefonoSec: "1511111114",
    contactoCorreo: "padre1@dominio.com"
  }).save();

  
  const personaPadre12 = await Persona({
    nombres: "Padre",
    apellidos: "N° 12",
    numeroDocumento: "4444412",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Chacabuco",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111115",
    contactoTelefonoSec: "1511111114",
    contactoCorreo: "padre1@dominio.com"
  }).save();

  
  const personaPadre13 = await Persona({
    nombres: "Padre",
    apellidos: "N° 13",
    numeroDocumento: "4444413",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Chacabuco",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111115",
    contactoTelefonoSec: "1511111114",
    contactoCorreo: "padre1@dominio.com"
  }).save();

  
  const personaPadre14 = await Persona({
    nombres: "Padre",
    apellidos: "N° 14",
    numeroDocumento: "4444414",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Chacabuco",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111115",
    contactoTelefonoSec: "1511111114",
    contactoCorreo: "padre1@dominio.com"
  }).save();

  
  const personaPadre15 = await Persona({
    nombres: "Padre",
    apellidos: "N° 15",
    numeroDocumento: "4444415",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Chacabuco",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111115",
    contactoTelefonoSec: "1511111114",
    contactoCorreo: "padre1@dominio.com"
  }).save();

  
  const personaPadre16 = await Persona({
    nombres: "Padre",
    apellidos: "N° 16",
    numeroDocumento: "4444416",
    tipoDocumento: "DNI",
    genero: "Masculino",
    grupoFactor: "B+",
    nacionalidad: "AR",
    fechaNacimiento: "1972-10-19T16:36:14.197Z",
    domicilioLocalidad: "San Fernando del Valle de Catamarca",
    domicilioCodigoPostal: 4700,
    domicilioBarrio: "Alem",
    domicilioCalle: "Av. Alem",
    domicilioNumeroCalle: 5555,
    domicilioPiso: 3,
    domicilioDepartamento: "Z",
    ocupacion: "Lic. Informatica",
    domicilioLaboralLocalidad: "Capital",
    domicilioLaboralCodigoPostal: 4700,
    domicilioLaboralBarrio: null,
    domicilioLaboralCalle: "Chacabuco",
    domicilioLaboralNumeroCalle: 599,
    domicilioLaboralPiso: null,
    domicilioLaboralDepartamento: null,
    contactoTelefono: "1511111115",
    contactoTelefonoSec: "1511111114",
    contactoCorreo: "padre1@dominio.com"
  }).save();

return { 
  personaMadre1, 
  personaMadre2, 
  personaMadre3, 
  personaMadre4, 
  personaMadre5, 
  personaMadre6, 
  personaMadre7, 
  personaMadre8, 
  personaMadre9, 
  personaMadre10, 
  personaMadre11, 
  personaMadre12, 
  personaMadre13, 
  personaMadre14, 
  personaMadre15, 
  personaMadre16,
  personaPadre1, 
  personaPadre2, 
  personaPadre3, 
  personaPadre4, 
  personaPadre5, 
  personaPadre6, 
  personaPadre7, 
  personaPadre8, 
  personaPadre9, 
  personaPadre10, 
  personaPadre11, 
  personaPadre12, 
  personaPadre13, 
  personaPadre14, 
  personaPadre15, 
  personaPadre16
  }
}