const Persona = require("../../../models/Persona");
const colors = require("colors/safe");

exports.createPersonasAlumnos = async () => {
    console.log(colors.cyan("Persona - Alumnos"));
    
      const personaAlumno1 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 1",
      numeroDocumento: "2222221",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1991-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "3834534454",
      contactoTelefonoSec: null,
      contactoCorreo: "alumno1@siga.unca.com"
      }).save();
    
    const personaAlumno2 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 2",
      numeroDocumento: "2222222",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1991-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "03834028856",
      contactoTelefonoSec: null,
      contactoCorreo: "alumno2@siga.unca.com"
    }).save();
  
    const personaAlumno3 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 3",
      numeroDocumento: "2222223",
      tipoDocumento: "DNI",
      genero: "Femenino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1994-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Barrio las flores",
      domicilioCalle: "Av. Virgen del valle",
      domicilioNumeroCalle: 2076,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "0383402214",
      contactoTelefonoSec: null,
      contactoCorreo: "alumno3@siga.unca.com"
    }).save();
  
    const personaAlumno4 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 4",
      numeroDocumento: "2222224",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1994-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Parque chacabuco",
      domicilioCalle: "Presidente castillo",
      domicilioNumeroCalle: 25,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "0383404298",
      contactoTelefonoSec: null,
      contactoCorreo: "alumno4@siga.unca.com"
    }).save();
  
    const personaAlumno5 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 5",
      numeroDocumento: "2222225",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1994-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "La tablada",
      domicilioCalle: "Av. guemes",
      domicilioNumeroCalle: 250,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "0383404154",
      contactoTelefonoSec: null,
      contactoCorreo: "alumno5@siga.unca.com"
    }).save();
  
    const personaAlumno6 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 6",
      numeroDocumento: "2222226",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1994-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "La tablada",
      domicilioCalle: "Salta",
      domicilioNumeroCalle: 10,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "0383404153",
      contactoTelefonoSec: null,
      contactoCorreo: "alumno6@siga.unca.com"
    }).save();
    
    const personaAlumno7 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 7",
      numeroDocumento: "2222227",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1994-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Parque norte",
      domicilioCalle: "Maipu Norte",
      domicilioNumeroCalle: 33,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "0383404132",
      contactoTelefonoSec: null,
      contactoCorreo: "alumno7@siga.unca.com"
    }).save();

    const personaAlumno8 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 8",
      numeroDocumento: "2222228",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1992-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "03834020203",
      contactoTelefonoSec: '03834020203',
      contactoCorreo: "alumno@siga.unca.com"
    }).save();

    const personaAlumno9 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 9",
      numeroDocumento: "2222229",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1992-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "03834020203",
      contactoTelefonoSec: '03834020203',
      contactoCorreo: "alumno@siga.unca.com"
    }).save();

    const personaAlumno10 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 10",
      numeroDocumento: "2222210",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1992-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "03834020203",
      contactoTelefonoSec: '03834020203',
      contactoCorreo: "alumno@siga.unca.com"
    }).save();

    
    const personaAlumno11 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 11",
      numeroDocumento: "2222211",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1992-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "03834020203",
      contactoTelefonoSec: '03834020203',
      contactoCorreo: "alumno@siga.unca.com"
    }).save();

    
    const personaAlumno12 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 12",
      numeroDocumento: "2222212",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1992-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "03834020203",
      contactoTelefonoSec: '03834020203',
      contactoCorreo: "alumno@siga.unca.com"
    }).save();

    
    const personaAlumno13 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 13",
      numeroDocumento: "2222213",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1992-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "03834020203",
      contactoTelefonoSec: '03834020203',
      contactoCorreo: "alumno@siga.unca.com"
    }).save();

    
    const personaAlumno14 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 14",
      numeroDocumento: "2222214",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1992-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "03834020203",
      contactoTelefonoSec: '03834020203',
      contactoCorreo: "alumno@siga.unca.com"
    }).save();

    
    const personaAlumno15 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 15",
      numeroDocumento: "2222215",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1992-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "03834020203",
      contactoTelefonoSec: '03834020203',
      contactoCorreo: "alumno@siga.unca.com"
    }).save();

    
    const personaAlumno16 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 16",
      numeroDocumento: "2222216",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1992-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "03834020203",
      contactoTelefonoSec: '03834020203',
      contactoCorreo: "alumno@siga.unca.com"
    }).save();

    
    const personaAlumno17 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 17",
      numeroDocumento: "2222217",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1992-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "03834020203",
      contactoTelefonoSec: '03834020203',
      contactoCorreo: "alumno@siga.unca.com"
    }).save();

    
    const personaAlumno18 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 18",
      numeroDocumento: "2222218",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1992-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "03834020203",
      contactoTelefonoSec: '03834020203',
      contactoCorreo: "alumno@siga.unca.com"
    }).save();

    
    const personaAlumno19 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 19",
      numeroDocumento: "2222219",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1992-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "03834020203",
      contactoTelefonoSec: '03834020203',
      contactoCorreo: "alumno@siga.unca.com"
    }).save();

    
    const personaAlumno20 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 20",
      numeroDocumento: "22222220",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1992-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "03834020203",
      contactoTelefonoSec: '03834020203',
      contactoCorreo: "alumno@siga.unca.com"
    }).save();

    
    const personaAlumno21 = await Persona({
      nombres: "Alumno",
      apellidos: "N° 21",
      numeroDocumento: "22222221",
      tipoDocumento: "DNI",
      genero: "Masculino",
      grupoFactor: "A+",
      nacionalidad: "AR",
      fechaNacimiento: "1992-10-19T16:36:14.197Z",
      domicilioLocalidad: "San Fernando del Valle de Catamarca",
      domicilioCodigoPostal: 4700,
      domicilioBarrio: "Piedra blanca",
      domicilioCalle: "Ruta N°2",
      domicilioNumeroCalle: 505,
      domicilioPiso: 0,
      domicilioDepartamento: null,
      ocupacion: null,
      domicilioLaboralLocalidad: null,
      domicilioLaboralCodigoPostal: null,
      domicilioLaboralBarrio: null,
      domicilioLaboralCalle: null,
      domicilioLaboralNumeroCalle: null,
      domicilioLaboralPiso: null,
      domicilioLaboralDepartamento: null,
      contactoTelefono: "03834020203",
      contactoTelefonoSec: '03834020203',
      contactoCorreo: "alumno@siga.unca.com"
    }).save();

    return  {
        personaAlumno1,
        personaAlumno2,
        personaAlumno3,
        personaAlumno4,
        personaAlumno5,
        personaAlumno6,
        personaAlumno7,
        personaAlumno8,
        personaAlumno9,
        personaAlumno10,
        personaAlumno11,
        personaAlumno12,
        personaAlumno13,
        personaAlumno14,
        personaAlumno15,
        personaAlumno16,
        personaAlumno17,
        personaAlumno18,
        personaAlumno19,
        personaAlumno20,
        personaAlumno21,
    }
}